import { StyleSheet } from 'react-native';
import { getShadowStyle } from '../utils/styles';
import { colors } from './commonStyles';

export const cattleDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    padding: 20,
    paddingTop: 40,
    paddingBottom: 30,
    alignItems: 'center',
  },
  identifier: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 5,
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.white,
    marginBottom: 10,
    textAlign: 'center',
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 10,
  },
  tag: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginHorizontal: 5,
    marginBottom: 5,
  },
  tagText: {
    color: colors.white,
    fontWeight: '500',
    fontSize: 14,
  },
  infoCard: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 15,
    margin: 10,
    ...getShadowStyle({ height: 2, elevation: 3, opacity: 0.1, radius: 4 }),
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 8,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  infoLabel: {
    fontSize: 15,
    color: colors.textLight,
    flex: 1,
  },
  infoValue: {
    fontSize: 15,
    color: colors.text,
    flex: 1,
    textAlign: 'right',
    fontWeight: '500',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    marginBottom: 20,
  },
  editButton: {
    backgroundColor: colors.secondary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginRight: 5,
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
  deleteButton: {
    backgroundColor: colors.error,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginLeft: 5,
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
  buttonText: {
    color: colors.white,
    fontWeight: '600',
    marginLeft: 8,
    fontSize: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: colors.textLight,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    width: '85%',
    ...getShadowStyle({ height: 4, elevation: 5, opacity: 0.2, radius: 8 }),
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 15,
    textAlign: 'center',
  },
  modalText: {
    fontSize: 16,
    color: colors.text,
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 22,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: colors.border,
    marginRight: 5,
  },
  confirmButton: {
    backgroundColor: colors.error,
    marginLeft: 5,
  },
  modalButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  backButton: {
    backgroundColor: colors.secondary,
    padding: 12,
    margin: 20,
    borderRadius: 8,
    alignItems: 'center',
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
  qrButtonContainer: {
    padding: 10,
    marginBottom: 30,
  },
  qrButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 8,
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
  qrModalContent: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    width: '90%',
    alignItems: 'center',
    ...getShadowStyle({ height: 4, elevation: 5, opacity: 0.2, radius: 8 }),
  },
  qrContainer: {
    padding: 20,
    backgroundColor: colors.white,
    borderRadius: 8,
    marginVertical: 20,
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
  qrInfo: {
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    marginBottom: 10,
    lineHeight: 24,
  },
  qrInstructions: {
    fontSize: 14,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
    fontStyle: 'italic',
  },
  qrButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  qrActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 8,
    marginHorizontal: 5,
  },
  shareButton: {
    backgroundColor: colors.secondary,
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
  closeButton: {
    backgroundColor: colors.border,
    ...getShadowStyle({ height: 2, elevation: 2, opacity: 0.1, radius: 4 }),
  },
}); 