import { StyleSheet } from 'react-native';
import { getShadowStyle } from '../utils/styles';
import { colors } from './commonStyles';

export const farmsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    padding: 20,
    paddingTop: 40,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  subtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: colors.textLight,
    marginTop: 10,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 18,
    color: colors.textLight,
    textAlign: 'center',
    marginTop: 10,
  },
  emptySubtext: {
    fontSize: 16,
    color: colors.textLight,
    textAlign: 'center',
    marginTop: 5,
  },
  listContainer: {
    padding: 10,
    paddingBottom: 80,
  },
  farmItem: {
    backgroundColor: colors.white,
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 6,
    padding: 15,
    ...getShadowStyle({ elevation: 3, height: 2, opacity: 0.15, radius: 4 }),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  farmName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  actionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    marginLeft: 10,
    padding: 5,
  },
  infoContainer: {
    marginTop: 5,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  infoText: {
    fontSize: 14,
    color: colors.textLight,
    marginLeft: 8,
  },
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    backgroundColor: colors.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    ...getShadowStyle({ elevation: 5, height: 3, opacity: 0.25, radius: 6 }),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 20,
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 20,
    ...getShadowStyle({ elevation: 4, height: 2, opacity: 0.2, radius: 5 }),
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalText: {
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    marginVertical: 15,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  saveButton: {
    flex: 1,
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginLeft: 5,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginRight: 5,
    borderWidth: 1,
    borderColor: colors.border,
  },
  saveButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  cancelButtonText: {
    color: colors.text,
    fontSize: 16,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: colors.error,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginLeft: 5,
  },
  confirmButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalButton: {
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
    width: '100%',
  },
  modalButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  // Estilos para la sección de personal
  staffContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  staffHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    padding: 15,
  },
  backButton: {
    marginRight: 10,
  },
  staffTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
  },
  staffScrollView: {
    padding: 10,
  },
  staffSection: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
    ...getShadowStyle({ elevation: 2, height: 1, opacity: 0.1, radius: 3 }),
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 10,
    marginLeft: 5,
  },
  staffCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
    backgroundColor: colors.inputBg,
    marginBottom: 8,
  },
  staffInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  staffName: {
    fontSize: 15,
    color: colors.text,
    marginLeft: 10,
  },
  removeButton: {
    padding: 5,
  },
  addStaffButton: {
    padding: 5,
  },
  addStaffSection: {
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  addStaffTitle: {
    fontSize: 15,
    color: colors.text,
    marginBottom: 10,
    marginLeft: 5,
  },
  emptyStaffText: {
    fontSize: 14,
    color: colors.textLight,
    textAlign: 'center',
    marginVertical: 10,
    fontStyle: 'italic',
  },
  viewCattleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  viewCattleButtonText: {
    color: colors.primary,
    fontSize: 15,
    marginRight: 8,
  },
}); 