import { StyleSheet } from 'react-native';
import { getShadowStyle } from '../utils/styles';
import { colors } from './commonStyles';

export const farmsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    padding: 20,
    paddingTop: 40,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  headerSubtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 5,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 18,
    color: colors.textLight,
    textAlign: 'center',
    marginTop: 10,
  },
  emptySubText: {
    fontSize: 16,
    color: colors.textLight,
    textAlign: 'center',
    marginTop: 5,
  },
  farmCard: {
    backgroundColor: colors.white,
    borderRadius: 10,
    marginHorizontal: 15,
    marginBottom: 15,
    ...getShadowStyle({ elevation: 3, height: 2, opacity: 0.15, radius: 4 }),
  },
  farmHeader: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  farmName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  farmLocation: {
    fontSize: 14,
    color: colors.textLight,
    marginTop: 3,
  },
  farmStats: {
    flexDirection: 'row',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
  },
  statLabel: {
    fontSize: 12,
    color: colors.textLight,
    marginTop: 3,
  },
  farmActions: {
    flexDirection: 'row',
    padding: 10,
  },
  actionButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  actionText: {
    fontSize: 12,
    color: colors.secondary,
    marginTop: 5,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    backgroundColor: colors.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    ...getShadowStyle({ elevation: 5, height: 3, opacity: 0.25, radius: 6 }),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 20,
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 20,
    ...getShadowStyle({ elevation: 4, height: 2, opacity: 0.2, radius: 5 }),
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 20,
    textAlign: 'center',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  button: {
    flex: 1,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButton: {
    backgroundColor: colors.primary,
    marginLeft: 5,
  },
  cancelButton: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 5,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  saveButtonText: {
    color: colors.white,
  },
  cancelButtonText: {
    color: colors.text,
  },
  staffContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  staffHeader: {
    backgroundColor: colors.primary,
    padding: 20,
    alignItems: 'center',
  },
  staffTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    marginTop: 10,
  },
  staffSubtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 5,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tab: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: colors.primary,
  },
  tabText: {
    fontSize: 14,
    color: colors.textLight,
  },
  activeTabText: {
    fontWeight: 'bold',
    color: colors.primary,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    margin: 15,
  },
  personCard: {
    backgroundColor: colors.white,
    flexDirection: 'row',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    alignItems: 'center',
  },
  personInfo: {
    flex: 1,
  },
  personName: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
  },
  personEmail: {
    fontSize: 14,
    color: colors.textLight,
  },
  personAction: {
    paddingHorizontal: 10,
  },
  messageModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  messageModalContent: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 20,
    width: '80%',
    ...getShadowStyle({ elevation: 4, height: 2, opacity: 0.2, radius: 5 }),
  },
  messageText: {
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    marginVertical: 20,
  },
  messageButton: {
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
  },
  messageButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  deleteModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  deleteModalContent: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 20,
    width: '80%',
    ...getShadowStyle({ elevation: 4, height: 2, opacity: 0.2, radius: 5 }),
  },
  deleteText: {
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    marginVertical: 20,
  },
  deleteButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deleteConfirmButton: {
    backgroundColor: colors.error,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    flex: 1,
    marginRight: 5,
  },
  deleteCancelButton: {
    backgroundColor: colors.background,
    padding:.12,
    borderRadius: 5,
    alignItems: 'center',
    flex: 1,
    marginLeft: 5,
    borderWidth: 1,
    borderColor: colors.border,
  },
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    backgroundColor: colors.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    ...getShadowStyle({ elevation: 5, height: 3, opacity: 0.25, radius: 6 }),
  },
  farmItem: {
    backgroundColor: colors.white,
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 6,
    padding: 15,
    ...getShadowStyle({ elevation: 3, height: 2, opacity: 0.15, radius: 4 }),
  },
}); 